name: "Servipagos deployment"

# Trigger this workflow whenever a pull request is opened against the repo's
# main branch or an existing pull request's head branch is updated.
on:
  push:
    branches:
      - main
    paths:
      - 'servipagos/**' # only start when something changes in this file directory

jobs:
  deploy_xandr_bundles:
    name: Deploy bundles
    uses: ./.github/workflows/deploy_bundle.yml
    with:
      BUNDLE_ENV: "prod"
      WORKING_DIR: "./servipagos"
    secrets:
      DATABRICKS_TOKEN: ${{ secrets.DATABRICKS_TOKEN }}
